# This is a basic workflow to help you get started with Actions

name: Change Secret Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Pick next target
        id: target-pick
        run: echo TARGET=$((1 + RANDOM % 100)) >> "$GITHUB_OUTPUT"

      - name: Set the target secret
        env:
          THE_SECRET: ${{ steps.target-pick.outputs.TARGET }}
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'TARGET_NUMBER'
          value: $THE_SECRET
          repository: richmr/actions-playground
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
