# This is a basic workflow to help you get started with Actions

name: Read Secret Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CURRENT_TARGET: ${{ secrets.TARGET_NUMBER }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-secret-change:
    # if:  ${{ env.CURRENT_TARGET == 50 }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Log it
        run: | 
          echo $CURRENT_TARGET > guessing_game/target.txt

      - uses: stefanzweifel/git-auto-commit-action@v5

      
