# This is a basic workflow to help you get started with Actions

name: Reset Guessing Game

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  reset-the-game:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Reset readme
        uses: canastro/copy-action@0.0.2
        with:
          # Source file
          source: guessing_game/.pages/StartPage.md
          # Target file
          target: guessing_game/readme.md

      - name: Delete last guess
        uses: JesseTG/rm@v1.0.3
        with:
          path: /guessing_game/myguess.txt

      - name: Pick next target
        id: target-pick
        run: echo TARGET=$((1 + RANDOM % 100)) >> "$GITHUB_OUTPUT"

      - name: Set the target secret
        env:
          THE_SECRET: ${{ steps.target-pick.outputs.TARGET }}
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'TARGET_NUMBER'
          value: $THE_SECRET
          repository: richmr/actions-playground
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
                

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
