# This is a basic workflow to help you get started with Actions

name: Test Secret

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
#env:
 # CURRENT_TARGET: ${{ secrets.TARGET_NUMBER }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-secret-equal:
    runs-on: ubuntu-latest
    env:
      CURRENT_TARGET: ${{ secrets.TARGET_NUMBER }}
    if: env.CURRENT_TARGET == 50
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: show-results
        run: |
          echo "### It was equal to 50" >> $GITHUB_STEP_SUMMARY
