# This is a basic workflow to help you get started with Actions

name: The Game

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - guessing_game/myguess.yml
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CURRENT_TARGET: ${{ secrets.TARGET_NUMBER }}
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: 'guessing_game/myguess.yml'          # File to read from
          key-path: '["guess"]' # Access the runs key then the using key and retuns the value.
      
      - name: Is It Low
        if: steps.yaml-data.outputs.data < env.CURRENT_TARGET
        uses: canastro/copy-action@0.0.2
        with:
          # Source file
          source: guessing_game/.pages/TooLow.md
          # Target file
          target: guessing_game/readme.md

      - name: Is It High
        if: steps.yaml-data.outputs.data > env.CURRENT_TARGET
        uses: canastro/copy-action@0.0.2
        with:
          # Source file
          source: guessing_game/.pages/TooHigh.md
          # Target file
          target: guessing_game/readme.md

      - name: Just Right
        if: steps.yaml-data.outputs.data == env.CURRENT_TARGET
        uses: canastro/copy-action@0.0.2
        with:
          # Source file
          source: guessing_game/.pages/GoodGuess.md
          # Target file
          target: guessing_game/readme.md

      - uses: stefanzweifel/git-auto-commit-action@v5
      
